# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{flightcaster}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jarod Luebbert"]
  s.date = %q{2010-03-01}
  s.description = %q{Simple interaction with the flightcaster API. Look up
    flight predictions and information.}
  s.email = %q{jarod.luebbert@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "examples/flights.rb",
     "flightcaster.gemspec",
     "lib/flightcaster.rb",
     "lib/flightcaster/base.rb",
     "lib/flightcaster/rash.rb",
     "lib/flightcaster/request.rb",
     "test/fixtures/airline.xml",
     "test/fixtures/airline_flight.xml",
     "test/fixtures/airline_flights.xml",
     "test/fixtures/airlines.xml",
     "test/fixtures/airlines_page.xml",
     "test/fixtures/airlines_per_page.xml",
     "test/fixtures/airport.xml",
     "test/fixtures/airports.xml",
     "test/fixtures/arrivals.xml",
     "test/fixtures/departures.xml",
     "test/fixtures/flight.xml",
     "test/fixtures/flight_date.xml",
     "test/fixtures/flight_path.xml",
     "test/fixtures/flight_path_date.xml",
     "test/fixtures/flights.xml",
     "test/fixtures/general_delay.xml",
     "test/fixtures/general_delays.xml",
     "test/fixtures/ground_delay.xml",
     "test/fixtures/ground_delays.xml",
     "test/fixtures/ground_stop.xml",
     "test/fixtures/ground_stops.xml",
     "test/fixtures/metar.xml",
     "test/fixtures/metars.xml",
     "test/fixtures/notfound.xml",
     "test/fixtures/oldapi.xml",
     "test/fixtures/taf.xml",
     "test/fixtures/tafs.xml",
     "test/helper.rb",
     "test/test_base.rb",
     "test/test_flightcaster.rb",
     "test/test_request.rb",
     "test/test_result.rb"
  ]
  s.homepage = %q{http://github.com/jarodluebbert/flightcaster}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Simple interaction with the flightcaster API}
  s.test_files = [
    "test/helper.rb",
     "test/test_base.rb",
     "test/test_flightcaster.rb",
     "test/test_request.rb",
     "test/test_result.rb",
     "examples/flights.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 2.10.2"])
      s.add_development_dependency(%q<shoulda>, [">= 2.10.2"])
      s.add_development_dependency(%q<mhennemeyer-matchy>, [">= 0.3.3"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.2.8"])
      s.add_runtime_dependency(%q<httparty>, [">= 0.5.2"])
      s.add_runtime_dependency(%q<hashie>, [">= 0.1.8"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 2.10.2"])
      s.add_dependency(%q<shoulda>, [">= 2.10.2"])
      s.add_dependency(%q<mhennemeyer-matchy>, [">= 0.3.3"])
      s.add_dependency(%q<fakeweb>, [">= 1.2.8"])
      s.add_dependency(%q<httparty>, [">= 0.5.2"])
      s.add_dependency(%q<hashie>, [">= 0.1.8"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 2.10.2"])
    s.add_dependency(%q<shoulda>, [">= 2.10.2"])
    s.add_dependency(%q<mhennemeyer-matchy>, [">= 0.3.3"])
    s.add_dependency(%q<fakeweb>, [">= 1.2.8"])
    s.add_dependency(%q<httparty>, [">= 0.5.2"])
    s.add_dependency(%q<hashie>, [">= 0.1.8"])
  end
end

